% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Feb-2023 10:05:54
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------





%of the form [t_0 0 0 0 0 0 0 0]
%t_0=51700;


%--Constants for any run--%
MuS=1.32747e20; % Mu for the Sun

rs=149597870700; % m distance from sun to earth

r0=(rs)*[1 0 0].';

v0=sqrt(MuS/norm(r0))*[0 1 0].';  % formula for velocity of a circular 

tperiod=2*pi*sqrt((r0(1,:)^3)/MuS); % formula for one orbit period

d_o= 2.28e+11; %specifes the target orbit

vmt= 24000; %mars orbital speed in m/s

e_m=0;


% 
% %---Min ISP---
% g=9.81;
% m_dot=0.0373;
% isp=1.2788e5;
% F=m_dot*g*isp;
% mass_init=200000;
% thrust=F;
% guess_init=[583000 0 0 0 0 0 0 0];




%--Tina's numbers
mass_init=250000;
thrust=0.019*mass_init*9.81;
m_dot=0.04;

guess_init=[651300 0 0 0 0 0 0 0];








%--0.5g---
% mass_init=15000;
% m_dot=0.02;
% guess_init=[126900 0 0 0 0 0 0 0];
% thrust=0.5*mass_init*9.81;
% opt_cooef = [126447.07628224068 -0.67883995080904058 2.2641912090027496 ...
%              -0.83011366760054539 0.074699585200471652 0.67512669880118481 ...
%              0.5881772316169217 -0.0032890612332791766];





% --1g accel----
% mass_init=15000;
% m_dot=0.028;
% opt_cooef=[89450 0 0 0 0 0 0 0];
% thrust=mass_init*9.81;



%--3g accel---

%opt 1
%mass_init=15000; %mass of spacecraft and fuel
%m_dot=0.053;
%guess_init=[51670 0 0 0 0 0 0 0];

%guess_init = [51615.04346918482 -0.099137840195730229 0.1294494108850951 ...
%              0.56368699321517957 0.02857920116379524 0.014875185682494296 ...
%              0.6535935855973225 -0.0030662051266524206];
% %thrust=3*mass_init*9.81;

% % %opt 2
% % mass_init=50000; %mass of spacecraft and fuel
% % m_dot=0.164;
% % opt_cooef = [51619.444859243929 -0.069809270038067833 -0.92995927256668742 ...
% %              0.65048352939845266 -0.77445278832133013 0.048876352306361781 ...
% %              1.0772928379695008 -0.013325296997034742];
% 
% thrust=3*mass_init*9.81; %use for both options



%--10 g--%
% %10 g conditions
% t_0=28266;
%m_dot=0.08;
%thrust=10*mass_init*9.81;
%tstop=187000
%guess_init=[t_0 0 0 0 0 0 0 0]; %initial guess of cooef.
